// ui-prototypes/apps/solid/src/main.tsx
import "ag-grid-community/styles/ag-grid.css";
import "ag-grid-community/styles/ag-theme-quartz.css";
import "@bakeoff/shared/tokens.css";
import { render } from "solid-js/web";
import App from "./App";

const MINIMAL = false;
if (MINIMAL) {
  render(() => <div style="color:gold;padding:20px;font-family:monospace">SOLID OK — setup works</div>, document.getElementById("root")!);
} else {
  render(() => <App />, document.getElementById("root")!);
}

// ui-prototypes/apps/react/src/main.tsx
import "ag-grid-community/styles/ag-grid.css";
import "ag-grid-community/styles/ag-theme-quartz.css";
import "@bakeoff/shared/tokens.css";
import React from "react";
import { createRoot } from "react-dom/client";
import App from "./App";

createRoot(document.getElementById("root")!).render(<App />);
